import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <main>
          <header>
            <nav>
              <ul className="flex gap-4">
                  <Link href="/" >
                    home
                  </Link>
                  <Link href="/notes" >
                    notes
                  </Link>
              </ul>
            </nav>
          </header>
          {children}
        </main>
      </body>
    </html>
  );
}
